# Generated by Django 3.1.3 on 2020-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img_file',
            field=models.ImageField(upload_to='marketing/'),
        ),
    ]
