# Generated by Django 3.1.3 on 2020-11-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20201119_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='img', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='img_file',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
